<?php

namespace backend\controllers;
use backend\components\AdminTrait;

class LanguageController extends \lajax\translatemanager\controllers\LanguageController
{
    public $section;

    public $topMenuItems = [
        ['label' => 'Actions', 'icon' => 'flaticon-add', 'url' => 'javascript:;', 'items' => [
            ['label' => 'Scan', 'url' => ['/translatemanager/language/scan'], 'icon' => 'flaticon-search'],
            ['label' => 'Optimize', 'url' => ['/translatemanager/language/optimizer'], 'icon' => 'flaticon-diagram'],
        ]]
    ];

    public function render($view, $params = [])
    {
        return parent::render($this->getNewViewPath($view), $params); // TODO: Change the autogenerated stub
    }

    protected function getNewViewPath($view)
    {
        if(in_array($view , ['list', 'translate'])) {
            $view = "@backend/views/language/{$view}";
        }

        return $view;
    }

}