<?php

namespace account\models;

use yii\base\Model;
use common\models\User;

use Yii;

class AccountSettingsForm extends Model
{
    public $first_name;

    public $last_name;

    public $company_name;

    public $address;

    public $zipcode;

    public $country;

    public $city;

    public $phone;

    public $email;

    public $password;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $user = $this->getUser();
        if($user) {
            $this->setAttributes($user->getAttributes([
                'email', 'first_name', 'last_name', 'company_name', 'address', 'zipcode', 'country', 'city', 'phone'
            ]));
        }
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [

            ['email', 'trim'],
            ['email', 'required'],
            ['email', 'email'],
            ['email', 'string', 'max' => 255],
            ['email',
                'unique',
                'targetClass' => '\common\models\User',
                'message' => 'This email address has already been taken.',
                'filter' => ['<>', 'user_id', Yii::$app->user->id]
            ],

            [['first_name', 'last_name', 'company_name', 'address', 'zipcode', 'country', 'city', 'phone'], 'string'],

            ['password', 'safe'],
            ['password', 'string', 'min' => 6],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
        ];
    }

    public function updated()
    {
        if (!$this->validate()) {
            return null;
        }

        $user = $this->getUser();
        if(!$user) {
            return null;
        }

        if($this->password) {
            $user->setPassword($this->password);
        }

        $user->setAttributes($this->getAttributes([
            'email', 'first_name', 'last_name', 'company_name', 'address', 'zipcode', 'country', 'city', 'phone'
        ]));

        return $user->save() ? $user : null;
    }

    public function getUser()
    {
        return User::findOne(Yii::$app->user->id);
    }

}
