<?php


namespace account\models;

use yii\base\Model;

use Yii;

class MoneyTransferModel extends Model
{
    public $country_id;

    public $transfer_type_id;

    public $transfer_agent_id;

    public $send_by;

    public $agency;

    public $amount_from;

    public $amount_to;

    public $currency_from_id;

    public $currency_to_id;

    public $comment;

    public $agree;


    /* TRANSFER BY MODELS */
    public $transferByMobileModel;
    public $transferByCardModel;
    public $transferByPickupModel;
    public $transferByBankModel;


    const SEND_BY_MOBILE = 'mobile';
    const SEND_BY_BANK   = 'bank';
    const SEND_BY_PICKUP = 'pickup';
    const SEND_BY_CARD   = 'card';


    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->transferByMobileModel = new TransferMoneyByMobile();
        $this->transferByBankModel   = new TransferMoneyByBank();
    }

    public function getSendByList() {
        return [
            self::SEND_BY_MOBILE => Yii::t('app', 'Send by mobile'),
            self::SEND_BY_BANK   => Yii::t('app', 'Send by bank'),
            self::SEND_BY_CARD   => Yii::t('app', 'Send by card'),
            self::SEND_BY_PICKUP => Yii::t('app', 'Send by pickup')
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['beneficiary_id', 'country_id', 'transfer_type_id', 'transfer_agent_id', 'send_by', 'amount_from', 'amount_to', 'currency_from_id', 'currency_to_id', 'agree'], 'required'],
            [['agree'], 'required', 'requiredValue' => 1, 'message' => 'Required field'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [

        ];
    }
}