<?php

namespace backend\widgets\tree;
use yii\base\Widget;
use yii\bootstrap4\Html;
use yii\helpers\Url;
use Yii;

class ActionButtons extends Widget
{

    public $template = '{view} {update} {delete}';

    public $buttons = [];

    public $action = '';

    public $buttonOptions = [];

    public $model;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->initDefaultButtons();

        echo Html::beginTag('div', ['class' => 'btn-group btn-group-sm']);
        foreach($this->buttons as $button) {
            echo $button($this->model);
        }
        echo Html::endTag('div');

    }

    protected function initDefaultButtons()
    {
        $this->initDefaultButton('view', 'eye');
        $this->initDefaultButton('update', 'edit');
        $this->initDefaultButton('delete', 'delete', [
            'data-confirm' => Yii::t('yii', 'Are you sure you want to delete this item?'),
            'data-method' => 'post',
        ]);
    }

    protected function initDefaultButton($name, $iconName, $additionalOptions = [])
    {
        if (!isset($this->buttons[$name]) && strpos($this->template, '{' . $name . '}') !== false) {
            $this->buttons[$name] = function ($model) use ($name, $iconName, $additionalOptions) {
                switch ($name) {
                    case 'view':
                        $title = Yii::t('yii', 'View');
                        break;
                    case 'update':
                        $title = Yii::t('yii', 'Update');
                        break;
                    case 'delete':
                        $title = Yii::t('yii', 'Delete');
                        break;
                    default:
                        $title = ucfirst($name);
                }

                $color = $name == 'delete' ? 'danger' : 'default';
                $options = array_merge([
                    'class' => 'btn btn-sm btn-' . $color,
                    'title' => $title,
                    'aria-label' => $title,
                    'data-pjax' => '0',
                ], $additionalOptions, $this->buttonOptions);
                $icon = Html::tag('i', '', ['class' => "flaticon-$iconName"]);
                $params['id'] = $model->primaryKey;
                $params[0] = $this->action ?: $name;
                return Html::a($icon, Url::to($params), $options);
            };
        }
    }
}