<?php

namespace backend\widgets;

use backend\widgets\bootstrap4\Html;
use yii\widgets\InputWidget;

class Image extends InputWidget
{
    public function init()
    {
        //parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {

        if ($this->hasModel()) {
            echo Html::activeTextarea($this->model, $this->attribute, $this->options);
        } else {
            echo Html::textarea($this->name, $this->value, $this->options);
        }
    }
}