<?php


namespace backend\widgets;

use yii\helpers\Url;
use yii\helpers\Html;
use yii\base\Widget;

class LangButtons extends Widget
{
    /**
     * @var Category model
     */
    public $model;

    public $languages = [];

    public $btnGroupCssClass = 'btn-group-sm';

    public $action = 'update';

    /**
     * @var string
     */
    public $languageAttribute = 'lang_id';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        echo Html::beginTag('div', [
            'class' => 'btn-group ' . $this->btnGroupCssClass
        ]);
        foreach ($this->languages as $lang_id => $lang) {
            $name = "update-$lang_id";

            /** @var \lav45\translate\TranslatedTrait $model */


            $params = ['id' => (string) $this->model->primaryKey];
            $params[$this->languageAttribute] = $lang_id;
            $params[0] = $this->action;

            $url = Url::toRoute($params);

//            $color = $this->model->hasTranslate($lang_id) ? 'info' : 'default';

            $color = $this->model->language == $lang_id ? 'info' : 'default';

            $options = [
                'class' => "btn btn-$color",
                'title' => "Edit $lang version",
                'data-pjax' => '0',
            ];

            echo Html::a($lang, $url, $options);
        }
        echo Html::endTag('div');
    }
}