<?php

namespace frontend\widgets;

use common\models\Currency;
use yii\base\Widget;

class CrossRates extends Widget
{
    function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    function run()
    {
        $models = Currency::find()->orderBy('weight ASC')->where(['visible' => 1])->all();
        return $this->render('crossRates', [
            'models' => $models
        ]);
    }
}