<?php

namespace frontend\widgets;

use yii\widgets\InputWidget;

use common\models\Currency;
use yii\helpers\ArrayHelper;
use yii\web\JsExpression;
use yii\helpers\Html;
use Yii;

class CurrencyCourse extends InputWidget
{
    public $labelOptions = [];

    public $type;

    const TYPE_CURRENCY = 'currency';
    const TYPE_AMOUNT   = 'amount';

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub

        if (!isset($this->labelOptions['class'])) {
            $this->labelOptions['class'] = 'form__currency';
        }
        $this->labelOptions['v-cloak'] = '';

        $this->registerAsset();

        if($this->type == self::TYPE_CURRENCY) {
            $this->labelOptions['v-if'] = 'CR_TO_ILS && currency';
            $html = Html::tag('span', Yii::t('app', '{{volume}} {{currency}} for {{CR_TO_ILS}} ILS'), $this->labelOptions);
            $html.= Html::tag('span', Yii::t('app', 'Currency can be ordered in multiples of {{multipleValue}} '), [
                'v-cloak' => '',
                'v-if' => 'multipleValue',
                'class' => 'form__info'
            ]);
            Html::addCssClass($this->field->wrapperOptions, '');

            $models  = Currency::getValidated()->andWhere(['for_order' => 1])->all();
            $options = Currency::getCurrencyOptions($models);

            return '<div class="uk-child-width-1-2@s" uk-grid><div class="form__wrap-select">' .  Html::activeDropDownList($this->model, $this->attribute,
                    ArrayHelper::map($models, 'currency_id', 'name'), [
                        'class'   => 'form__select',
                        '@change' => 'changeCurrency($event)',
                        'ref'     => 'currency',
                        'options' => $options
                    ]) .'</div></div>' . $html;


        } elseif($this->type == self::TYPE_AMOUNT) {
            $this->labelOptions['v-if'] = 'amountModel';
            $html = Html::tag('span', Yii::t('app', 'Total {{total}} ILS'), $this->labelOptions);
            $html.= Html::tag('span', Yii::t('app',  "{{ errors.first(\"CurrencyOrderForm[amount]\") }}"), [
                'v-cloak' => '',
                'class' => 'form__info-error'
            ]);


            Html::addCssClass($this->field->wrapperOptions, '');
            $inputFrom = '<div class="uk-margin-small-bottom">' . Html::activeInput('number', $this->model, $this->attribute, [
                'v-model.number' => "amount['from']",
                '@input' => "doConvert('from')",
                'data-vv-as' => ' ',
                'v-validate' => "'amountModelMultiple'",
                'class' => 'form-control'
            ]) .'</div>';

            $inputTo = '<div class="uk-margin-small-bottom"><div class="uk-position-relative">' . Html::textInput('number', '', [
                'v-model.number' => "amount['to']",
                '@input' => "doConvert('to')",
                '@blur' => 'validateData',
//                'v-validate' => "'amountModelMultiple'",
                'class' => 'form-control'
            ]) .'<span class="form__info">'. Yii::t('app',  "Currency in ILS").'</span></div></div>';
                return '<div class="uk-child-width-1-2@s  uk-grid">' . $inputFrom .  $inputTo .'</div>' .$html ;

        }
    }

    function registerAsset()
    {
        $this->getView()->registerJsFile('/js/currencyCalc.js', [
            'depends' => [
                'frontend\assets\VendorAsset'
            ]
        ]);
    }
}
