<?php

namespace frontend\widgets;

use yii\base\Widget;

use Yii;

class LanguageSelector extends Widget
{

    private $_isError;

    public $items = [];

    function init()
    {
        $route = Yii::$app->controller->route;
        $appLanguage = Yii::$app->language;
        $params = $_GET;
        $this->_isError = $route === Yii::$app->errorHandler->errorAction;

        array_unshift($params, '/' . $route);

        foreach (Yii::$app->urlManager->languages as $language) {
            $isWildcard = substr($language, -2) === '-*';
            if (
                $language === $appLanguage ||
                // Also check for wildcard language
                $isWildcard && substr($appLanguage, 0, 2) === substr($language, 0, 2)
            ) {
                continue;   // Exclude the current language
            }
            if ($isWildcard) {
                $language = substr($language, 0, 2);
            }
            $params['language'] = $language;
            $this->items[] = [
                'label' => strtoupper($language),
                'url' => $params,
            ];

//            var_dump($this->items); exit;
        }

        parent::init(); // TODO: Change the autogenerated stub
    }


    function run()
    {
        // Only show this widget if we're not on the error page
        if ($this->_isError) {
            return '';
        }

        return $this->render('languageSelector');
    }

}