<?php

namespace frontend\widgets;

use common\models\PageRating;
use frontend\models\PageRateForm;
use yii\base\Widget;

use Yii;

class PageUseful extends Widget
{
    public $url;

    public $disabled;

    public function init()
    {
        if(!$this->url) {
            $this->url = Yii::$app->request->url;
        }

        $model = PageRating::findOne(['url' => $this->url]);
        if(!$model) {
            $model = new PageRating();
            $model->url = $this->url;
            $model->save(false);
        }

        if($this->disabled === null) {
            $cookieData = PageRateForm::getUrlsFromCookie();
            $this->disabled = in_array($this->url, $cookieData);
        }

        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        return $this->render('pageUseful');
    }
}