<?php

namespace backend\actions;

use yii\base\InvalidConfigException;
use yii\base\Action;
use yii\db\ActiveRecord;
use yii\helpers\ArrayHelper;

use Yii;

class SortAction extends Action
{
    /**
     * @var
     */
    public $model;

    /**
     * @var string
     */
    public $orderParamName = 'weight';

    function init()
    {
        if($this->model===null) {
            throw new InvalidConfigException('param Model must be specified');
        }

        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $modelName = $this->model;
        $primaryKey = $modelName::primaryKey()[0];

        $sortElements = (array)Yii::$app->request->get('sortElements', []);
        $models = ArrayHelper::index($modelName::find()->where(['in', $primaryKey, $sortElements])->all(), $primaryKey);

        $count = count($sortElements);
        foreach($sortElements as $id) {
            var_dump($count, $id);
            if(isset($models[$id])) {
                $models[$id]->{$this->orderParamName} = $count--;
                $models[$id]->save(false);
            }
        }
    }
}